name: GitHub Actions

on: [push]
jobs:
  build-and-test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64 , arch: amd64 }
          - { sys: mingw32, env: i686, arch: 386 }
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
      - name: Build executables
        env:
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 1
        shell: msys2 {0}
        run: |
          mkdir build
          gcc -o build/test-discon_${{ matrix.env }}.dll test-discon/test-discon.c --shared -g
          gcc -o build/test-app_${{ matrix.env }}.exe test-app/test-app.c -g
          go build -o build/discon-server_${{ matrix.env }}.exe discon-wrapper/discon-server
          go build -buildmode=c-shared -o build/discon-client_${{ matrix.env }}.exe discon-wrapper/discon-client
      - uses: actions/upload-artifact@v4
        with:
          name: windows-binaries-${{ matrix.env }}
          path: build/*

  # build-and-test-linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
  #     - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
  #     - name: Check out repository code
  #       uses: actions/checkout@v4
  #     - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
  #     - name: List files in the repository
  #       run: |
  #         ls ${{ github.workspace }}
